### ISSUE TITLE
Navrh gui aplikace

### ISSUE THREAD

**Issue by Drimix20** [Drimix20/PB138-RSS-ctecka#1]

**Comment by rzember** [comment]
Do wiki som pridal prvý návrh GUI, ak máte nejaké návrhy/námietky, prípadne ak som na niečo zabudol, tak sem s tým. Lepšie rozlíšenie na http://i.imgur.com/manpFmn.png

**Comment by Drimix20** [comment]
![rssctecka-gui](https://cloud.githubusercontent.com/assets/7419456/7386163/fbe55c56-ee50-11e4-9f8d-aed68127013d.png)

**Comment by Drimix20** [comment]
Pěkné :)

**Comment by rzember** [comment]
Pridal som "nahú" verziu UI zatiaľ bez funkcií (okrem tlačidla Close), obrázok znovu vo wiki. 

full res http://i.imgur.com/jd2Tcfp.png

**Comment by mayoturis** [comment]
Prepáč, že ťa zavraciam až teraz, ale až teraz som si všimol, že tam chýba tlačítko pre export do XHTML :)

**Comment by rzember** [comment]
Vidím to tak, že sa to bude robiť automaticky pri pridaní feedu: získa sa xml dokument -> transformuje sa cez šablónu na html súbor, ktorý sa uloží a zobrazí v aplikácii.

**Comment by mayoturis** [comment]
Teraz som zmätený trochu :) Myslel som si, že feedy sa nebudú zobrazovať v aplikácii ako html. Iba pri transformovaní ukladať do súbora.

**Comment by Drimix20** [comment]
Kazdopadne feedy se zatim ukladaji do objektu, takze pro zobrazovani by se musely prevest na xml a pak pomoci transformace na html.
