### ISSUE TITLE
FormGuardedBlockError

### ISSUE THREAD

**Issue by mayoturis** [Drimix20/PB138-RSS-ctecka#10]
Keď som otvoril design v gui, vyskočila mi chyba. Keď som sa pozrel do kódu tak vygenerovaný kód (initComponents, premenné) nebol nijako chránený (dal sa upravovať). Celý popis chyby:

> The form seems to be corrupted. The GUI builder is not able to find the sections with the generated code. The special comments that denote the start and the end of these sections were removed or modified. The form will be opened in read-only mode. See http://wiki.netbeans.org/FormGuardedBlockError for additional information.

Podľa tej url som teda vložil tie značky a zdá sa, že to už funguje. Píšem to iba ako upozornenie, lebo neviem či to tak bolo nachvál, alebo či som tým niečo neporušil

**Comment by mayoturis** [comment]
Napokon som dal tie značky preč, lebo ak som chcel upraviť gui pomocou designera, upravovalo už vytvorený kód pre iné tlačítka a vznikali chyby. Tlačítko pre export do HTML som teda vytvoril čisto cez kód, v designe ho preto ani nie je vidno.

**Comment by Drimix20** [comment]
Ja se pridavam, nevim proc, ale nejak nefunguje kliknuti na tlacitko selectCategory. Kdyz na nej kliknu, obsluzna metoda se vubec nezavola. Zkousel jsem si vypsat informace logem a nic. @rzember mohl by ses na to podivat?

**Comment by mayoturis** [comment]
Neviem či to dobre chápem, ale v obsluhe pre tlačítko s popisom "Select Category" nie je žiaden kód (funkcia selectCatButtonActionPerformed). Ak do tej funkcie napíšem napr. vyhodenie výnimky tak sa to normálne prevedie. 

Potom tam ale vidím kód vo funkcii categorySelectorActionPerformed, ktorá ale obsluhuje combobox s kategóriami (neviem akým spôsobom). Pripadá mi to tak, že kód z tejto funkcie by mal byť v tej funkci selectCatButtonActionPerformed ... ale to je len domnienka, neviem ako presne to má fungovať :)

**Comment by rzember** [comment]
Mne to funguje normalne
http://i.imgur.com/9b5TWE4.png

**Comment by Drimix20** [comment]
Aha, ja jsem to teda vlozil do spatne metody :) Diky.
Update: Opraveno

**Comment by Drimix20** [comment]
Tak nekomu IDE nejak predelava definici gui, takze pak netbeans neni schopen k nemu pristoupit a editovat ho. Je to ponekud blby, kdyz nemuzu vlastni kod upravovat :D
