### ISSUE TITLE
Odstranit z kategorie

### ISSUE THREAD

**Issue by Drimix20** [Drimix20/PB138-RSS-ctecka#12]
Po kliknuti se zobrazi dialog s vyberem moznosti.

**Comment by Drimix20** [comment]
Jakym zpusobem jsme rekli, ze to removeFromCat bude fungovat?

**Comment by rzember** [comment]
Presunut to cele do dialogoveho okna, vyber kategorie zo zoznamu, po vybere kategorie sa zobrazia feedy v tej kategorii a uzivatel si zvoli, ktory chce odstranit.

Aspon tak sa mi zda, mozno to bolo inak.

**Comment by mayoturis** [comment]
To sa mi zdá dosť zložité :) Zatiaľ to fugnuje tak, že feedu ktorý je vybraný v hornom comboBoxe nastavý kategóriu na none (teda bez kategórie). Pre mňa by to mohlo ostať aj takto. Alebo aj tak ako píše Richard ale to je práca naviac :)

**Comment by Drimix20** [comment]
Ja bych to asi udelal podle toho, co napsal Richard, protoze to mi pride lepsi. To z tech comboboxu neni moc vhodny. Kdyz vyberu zdroj a kategorii, kterou nema nastavenou, co se stane? Musim si teda pamatovat kategorii?.. Je to otazka jen chvilky, guiicko mam hotovy a kod bude taky behem chvilky.
