### ISSUE TITLE
Aktualizácia feedContaineru

### ISSUE THREAD

**Issue by mayoturis** [Drimix20/PB138-RSS-ctecka#15]
Chcem sa spýtať ako sa bude "zachytávať" úprava feedContianeru. Lebo vždy keď sa zmení je nutné zapísať ho do súboru a potom aktualizovať GUI (TextPane aj ComboBox). Ale keďže to beží vo vlastnom vlákne nejako na to nemôžem prísť :)

**Comment by Drimix20** [comment]
Jedine, co me napada, tak je zkusit doimplementovat PropertyChangeListener do RssFeedContaineru pri pridavani prvku.Ja se na to podivam a zkusim to vymyslet nejak na zaklade eventu, ze doslo ke zmene mapy a tak se provede kod pro aktualizaci...

**Comment by Drimix20** [comment]
Ja se pridavam, nevim proc, ale nejak nefunguje kliknuti na tlacitko selectCategory. Kdyz na nej kliknu, obsluzna metoda se vubec nezavola. Zkousel jsem si vypsat informace logem a nic. Richarde mohl by ses na to podivat?

**Comment by Drimix20** [comment]
Zdarec, takze jsem vytvoril intefrace ContainerChangeListener, je tam i ukazkova verze implementace, ktera po zmene containeru napise do logu, ze kontainer se zmenil a ja muzu jeho obsah vypsat. V ReaderUI pak nastavuji listener pro container. Tak se na to mrkni a v te metode containerChanched bude kod pro ulozeni a transformaci. Zkus se na to podivat, jestli ti to tak bude pasovat.

**Comment by mayoturis** [comment]
Áno páči sa mi to :) Ešte sa ale chcem spýtať ... bude potrebné aby po zmene containeru sa aktualizovalo GUI a teda v tej metóde containerChanged bude treba prístup k prvkom. Spravím to tak, že si vytvorím v ReaderUI vnútornú triedu ktorá implementuje ContainerChangeListener a tam s nimi budem manipulovať?

**Comment by Drimix20** [comment]
Diky. Bud a nebo je predat v konstruktoru te implementace. Vsechno jsou to objekty. Zkus ten konstruktor.
