### ISSUE TITLE
CheckboxListCellRenderer

### ISSUE THREAD

**Issue by mimaboci** [Drimix20/PB138-RSS-ctecka#16]
akym rozumnym sposobom spravim, aby sa v liste s tymto cell renderom dalo selectnut ako v checkboxoch?

**Comment by Drimix20** [comment]
Zalezi, jak to presne myslis. Pokud chces v gui, tak musis pomoci gui editory vytvorit obecny JList a nastavit mu cellRenderer na nas CheckboxListCellRenderer:
//obsahuje popis pro kazdy checkbox element
DefaultListModel<Category> listModel = new DefaultListModel<>();
        for (Category cat : cman.getAllCategories()) {
            if (!cat.getName().equals("none"))
                listModel.addElement(cat);
        }
jList1 = new javax.swing.JList();
jList1.setModel(this.listModel);
jList1.setCellRenderer(new CheckboxListCellRenderer());

Multiple choice pak zatim jde pouze jen pomoci SHIFT+vyber.

**Comment by Drimix20** [comment]
A muzes prosim te jeste projit ty issues co mam/e a pokud je tam neco uz hotovy, tak to zavrit?

**Comment by mimaboci** [comment]
prave ten multiple choice ma trapi

**Comment by Drimix20** [comment]
Tak ten multiple choice jsem uz spravil. Stacilo implementovat vlasti SelectionModel:
        jList1.setSelectionModel(new CheckboxSelectionModel());
        jList1.setSelectionMode(SelectionMode.MULTIPLE.ordinal());
U removeFeedDialog a deleteCategoryDialog jsem to uz upravil. U SearchDialogu mi to nejak nefunguje. Zkus se na to podivat.
