### ISSUE TITLE
Obhajoba

### ISSUE THREAD

**Issue by mayoturis** [Drimix20/PB138-RSS-ctecka#17]
Chcem sa spýtať ako to vidíte s dokončením aplikácie? Chcel by som totiž napísať email p. Rambouskovi ako je to s obhajobou, prípadne sa dohodnúť na termíne. Tak len či by sme mohli obhajovať už v piatok. Prípadne potom v pondelok. Či to teda stihneme dokončiť?

**Comment by Drimix20** [comment]
Nas projekt musi byt odevzdany 3 dny dopredu ne? Myslim, ze obhajobu v patek asi nedame.

**Comment by mayoturis** [comment]
ja som myslel, že sa nemusí odovzdávať, lebo podľa organizačných pokynov sa ešte môže aj po tom termíne upravovať. Aj keď už skôr len dolaďovať. Ani odevzdávarna nie je na to vytvorená.

Každopádne sa ešte chcem spýtať či ak by to teda klaplo máte čas v piatok prípadne pondelok na obhajobu?

**Comment by Drimix20** [comment]
Ja jsem oba dva dny v praci, ale muzu si odbehnout. Aha, tak dobre. Myslim si, ze to muze klapnout.

**Comment by Drimix20** [comment]
Ahoj, tak jsem mel pravdu. Tady se pise, ze projekt musi byt odevzdan 72 hodin pred obhajobou https://is.muni.cz/auth/el/1433/jaro2015/PB138/op/Hodnoceni_vyuky_a_organizace_projektu.html#projekty. A odevzdavarna neni potreba, protoze vyucujici i nas vedouci maji primy pristup k repozitari. Takze pokud bychom meli obhajobu v patek, tak musime odevzdat dneska v noci.

**Comment by mayoturis** [comment]
to som čítal ale technicky vzaté je tam napísané iba, že musí byť ukončený hlavný vývoj (ak som niečo neprehliadol) čo by možno aj mohol byť ... ale ok teda, každopádne by som mu dnes najneskôr zajtra napísal mail, radšej skôr ako neskôr ale ten pondelok už by to naozaj mohlo byť :)

**Comment by Drimix20** [comment]
Pokud mas cas, tak prosim projdi wiki a ty tasky, z tasku zavri, co je hotove a vytvor tasky na to, co nam jeste chybi. Ja se zkusim pak behem dne na neco vrhnout. Treba se nam to podari behem dneska/zitrka dam dohromady

**Comment by mayoturis** [comment]
Práve teraz nemám :/ Vrátim sa až po piatej tak potom sa kuknem na niečo

**Comment by Drimix20** [comment]
Aha, dobre.

**Comment by mayoturis** [comment]
písal som mail a teda termín na obhajobu je 26.6., zatiaľ tam nie je voľný termín, ale mal by byť pridaný ďalší

**Comment by mayoturis** [comment]
Bol pridaný voľný termín 26.6 16:40 ... prihlásil som nás na neho kým sa neobsadí, dúfam, že vám to vyhovuje, lebo veľmi si už nenavyberáme :)

**Comment by Drimix20** [comment]
Dobre, ja jsem pro :)
