### ISSUE TITLE
Error: JComboBox pro RssFeed a Category

### ISSUE THREAD

**Issue by Drimix20** [Drimix20/PB138-RSS-ctecka#18]
Nedari se mi nijak naplnit comboBoxy hodnotami, ktere by uzivatel mohl vybrat. Implementace u feedSelectoru nefunguje. Navic by ani nebylo dynamicke. Tedy po pridani noveho zdroje by nebyl videt v comboBoxu.
UPDATE: Jedna se o to, ze feedContainer je v dobe inicializace prazdny, takze se nema co pridat.

**Comment by Drimix20** [comment]
Jeste mam dotaz, ten ComboBox se vytvari podle hodnot ze stazeneho RssFeedu, takze se vklada nazev podle te stranky, napriklad "Zive.cz", "PcTunning RSS" atd. Nemel by ten vyber byt spis zalozen na pojmenovani podle toho zdroje? Teda podle toho, jak si to pojmenuje ten uzivatel? Napr. "Test", "Zdroje.cz". @mimaboci

**Comment by mimaboci** [comment]
ako sa dostanem od tasku k feedu?

**Comment by mimaboci** [comment]
ked dam addfeed tak sa nema stiahnut feed do containeru? lebo ak nie, tak ak budem mat v comboboxe task label, nebudem moct odpovedajuci feed zaradit do kategorie, lebo este neexistuje

**Comment by mimaboci** [comment]
ten addfeed mi nefunguje :)

**Comment by mayoturis** [comment]
mne funguje tak, že do containera začne sťahovať feedy až po znovuotvorení aplikácie

**Comment by Drimix20** [comment]
Tak to vypada, ze se spatne zaktualizuje downloader po vlozeni feedu pres gui. Melo by stacit se podivat na zpusob implementace metody addFeed. Protoze pokud po restartu aplikace vse funguje. Tak configurace se zparsuje spravne... Ja se bohuzel na to ted podivat nemuzu. Ale myslim, ze tam bude teda jen mala chybicka...

EDIT: @mimaboci @mayo505  tak jsem udelal kratky vyzkum a vypada to, ze je to tim, ze se v metode schedule v RssFeedDownloaderu akorat preda reference do olderTask. To je potreba upravit na nove vytvoreni bez reference.

**Comment by Drimix20** [comment]
FIX: uz by to melo byt ok, ale radeji to taky jeste zkontrolujte
