### ISSUE TITLE
Remove feed issue

### ISSUE THREAD

**Issue by mayoturis** [Drimix20/PB138-RSS-ctecka#19]
Neviem čím to je, ale keď chcem odstrániť nejaký feed tak neodstráni označený ale prvý. A ani konfiguračný súbor neupraví

**Comment by Drimix20** [comment]
Podivam se na to odstranovani nejen prvniho prvku. Konfiguracni soubor se upravuje pouze po zavreni aplikace, ale udelam to i pro kazdou zmenu.

**Comment by mayoturis** [comment]
aha, stačí podľa mňa iba pri zavrení, ja som ju zatváral X-kom namiesto tlačítka close tak preto mi to nešlo

**Comment by Drimix20** [comment]
Aha, tak to potom jo. Je to namapovany pouze na close button. Tim padem by ale nebylo spatny, abych funkcionalitu pri ukonceni RssReaderu udelal i pro ukonceni krizkem ;)

Update: DONE
