### ISSUE TITLE
Šablony pro export do xhtml

### ISSUE THREAD

**Issue by Drimix20** [Drimix20/PB138-RSS-ctecka#2]
Exportovanie načítaných feedov do XHTML, uživateľ by mal byť schopný okrem klasického exportu všetkých feedov si aj zvoliť ktoré kategórie chce exportovať, prípadne konkrétne ktoré zdroje.

**Comment by mayoturis** [comment]
Keďže v žiadnej issue nebolo napísané ukladanie načítaných feedov do xml pre offline čítanie a vo wiki to máme tak som to spravil. Ukladá sa to vo formáte

``` xml
<sources>
   <source url="[url z kadiaľ boli feedy sťahované]">[obsah prvého zdroja v rovnakom formáte ako              
                                                                                obsah elementu channel v rss]</source>
   <source url="...">...</source>
   ...
</sources>
```

Ako som písal v popise commitu samotné ukladanie asi nie je riešené najinteligentnejšie, ale nevedel som či takýto formát je v pohode tak som tam len lepil stringy. Preto ma zaujíma váš názor :) Z toho xml by sa potom transformáciou robilo xhtml.

**Comment by Drimix20** [comment]
Dobra prace :) Jen mam dotaz, momentalne teda vsechno z RssFeedContaineru ukladas do 1 souboru?

**Comment by mayoturis** [comment]
áno 1 container = 1 súbor. Spravil som to tak kvôli jednoduchosti a aby sa potom jednoduchšie robila transformácia do xhtml (v jednom xhtml budú môcť byť feedy od viacerých zdrojov). Ak by to vadilo môžem to upraviť, akurát by som chcel naisto vedieť ako to bude vyzerať nech na to môžem urobiť xslt (a pravdepodobne aj xml schema)

**Comment by Drimix20** [comment]
Jj, rozumim. Ja myslim, ze nejak takto by to mohlo byt, jeste bychl mel dotaz k te kategorizaci. Jeste jsem pridal komentar k tvemu commitu.
1) Nemeli bychom i nejakym zpusobem ukladat ty kategorie? 
2) Kdyz teda stahnu message, vlozim je do kontaineru ke spravnemu zdroji (jeste moje implementace) a pak vsechno znovu zapisu do 1 souboru ze? Tzn. prepisu drivejsi informace? Takze o to, co nemam v kontaineru, ale jen v souboru, tak pri dalsim zapisu ztratim?

**Comment by mayoturis** [comment]
1. asi mali ale neviem ako to má Miša vymyslené tak som to tam neriešil. Ale mohli by sa napríklad ukladať do vlastného súboru a element <source> by obsahoval atribut s menom/id danej kategórie. Tým by sa vedelo ku ktorej kategórii daný zdroj patrí. 
2. Áno ... myslel som, že by to mohlo fungovať tak, že zo súbora by sa do containera načítali uložené feedy. Z url by sa stiahli a do (iného alebo toho istého) containeru načítali nové feedy, to by sa nejako skombinovalo a prepísalo starý súbor. Zdalo sa mi jednoduchšie riešiť to už v načítaných objektoch ako až pri zápise do súbora podľa toho čo súbor obsahuje/neobsahuje. Lebo veľa krát stiahnuté itemy budú tie isté ako sú už v súbore. Akurát sa bude musieť stále načítavať celý súbor. Alebo to "kombinovanie" by nemuselo byť a rovno by novo stiahnuté dáta prepísali staré.

Čo si o tom myslíš? :)

**Comment by Drimix20** [comment]
Aha, rozumim. Feedy jsou ukladany do mnoziny, takze duplicity se nevyskytuji, ale podle me by toto vedlo k hodne spatne sprave pameti. Aplikace bude dlouho bezet, vsechno ulozi do souboru a pak se vypne. Po nejake dobe zase zapne a vsechno ze souboru se nahrne do pameti (obrovske mnozstvi dat) -> do objektu. Asi bychom to meli vymyslet nejak jinak... Z toho plyne dalsi otazka, jake informace chceme uchovavat? Vsechny a nebo par poslednich? Pokud ukladame do xml, tak bychom mohli vsechny.

**Comment by mayoturis** [comment]
To je pravda. Pôvodne som myslel, že by sa ukladal iba určitý počet najnovších feedov (napríklad 30) a ak by tých zdrojov nebolo vyslovene veľa s pamäťou by nemusel byť až taký problém. Lebo vlastne (ak to dobre chápem) ten objem dát by bol rovnaký ako pri stiahnutí (aj keď tam sa nemusia stiahnúť a zobraziť všetky zdroje naraz). Samozrejme môžme ukladať všetky ale to načítavanie by asi ostalo na tebe lebo neviem či je v mojich možnostiach načítanie z daného xml súbora iba nejakej časti (resp. nejakého elementu podľa podmienok). Alebo by potom mohol mať každý zdroj vlastný súbor (ale aj tak tých feedov môže byť časom priveľa), inak neviem ako :)

**Comment by Drimix20** [comment]
Ja prave nevim, jakym zpusobem to udelat. Napadlo me, ze bych si nekam zaznacil datum, kdy jsem naposledy stahoval feedy a pak je porovnal s feedama, ktere obdrzim a ulozim do xml souboru pouze ty, ktere jsou novejsi. A zase zmenim datum stahovani (pokud je novejsi). Ale je to jen takovej nastrel.

Ale bylo by dobry, kdyby se vyjadrili i ostatni. Treba budou mit lepsi napady.

**Comment by mayoturis** [comment]
Vytvoril som šablónu pre export do HTML aj so vzorovým súborom.

**Comment by mayoturis** [comment]
keďže som to už potreboval, vytvoril som veľmi jednoduchú šablónu pre zobrazovanie prvkov. Nefunguje mi tam CSS tak to nevyzerá bohvieako. Navyše to nie je zoraďované podľa času, nevedel som ako

**Comment by rzember** [comment]
na zoradenie sa pouziva <xsl:sort>, vid 
http://www.w3schools.com/xsl/el_sort.asp

**Comment by mayoturis** [comment]
to je mi jasné, ale ten sort radí buď podľa abecedy, alebo podľa čísla, nie podľa dátumu, navyše keď ten dátum je v divnom formáte ... keď tak sa skús na to pozrieť a dopísať to, ak na niečo prídeš

**Comment by rzember** [comment]
Idem sa na to mrknut, vsimol som si, ze ani hyperlinky nefunguju, tak skusim spravit aj to

**Comment by rzember** [comment]
hyperlinky by mali fungovat

**Comment by rzember** [comment]
Dneska som si pri vytvarani XSLT sablony kontroloval postup hlavne tlacidlom Show All a vsimol som si  zvlastnu vec - pri vytvarani docasneho suboru na zobranezie (temporary-feeds.xml) sa do itemov z urcitych zdrojov nezapisuje datum publikovania. Mozno bude chyba v RssFileWriter.

**Comment by mayoturis** [comment]
Tiež som si to všimol, ale myslel som si, že je to preto, že ho proste už nemal vyplnený zdroj keď sa sťahoval z netu, tak som tomu nevenoval pozornosť. Skúsim sa na to ešte pozrieť.

**Comment by mayoturis** [comment]
Dúfam, že som to už upravil, dátum som ukladal do chybne označeného elementu tak by to už hádam malo byť správne

**Comment by rzember** [comment]
jj zda sa, ze to funguje ako ma, uz som aj ten sort spravil
