### ISSUE TITLE
Chyba v GUI

### ISSUE THREAD

**Issue by mayoturis** [Drimix20/PB138-RSS-ctecka#21]
Keď sa do jTextPane1 zobrazí dlhé html, gui sa správa nejako zvláštne. Keď zmením veľkosť tak to nejako preskočí a skryje tlačítko close. Občas to urobí aj pri iných udalostiach. Netuším čím to môže byť skúšal som tomu jTextPane nastaviť pevnú veľkosť ale bez úspechu

UPDATE: Jedna z tých iných udalostí je aj napríklad zavrenie niektorého z vyskakovacích okien (okrem select category tam to nerobí) .... ozaj divné

**Comment by rzember** [comment]
Ahoj, skus zmenit jTextPane na jEditorPane, malo by to byt na zobrazovanie html vhodnejsie. Uz som to planoval spravit ja, ale mam zajtra este jednu skusku a chcem, aby uz bola posledna :D

**Comment by mayoturis** [comment]
skúšal som to, nefungovalo to ani tak, tak som zmeny ani neuložil

**Comment by rzember** [comment]
Môžeš sem dať screenshot? Ja som si totiž u seba nič nevšimol

**Comment by mayoturis** [comment]
aha tak už sa zdá, že je to OK, ospravedlňujem sa :)
