### ISSUE TITLE
Korektni odstraneni RssFeedu

### ISSUE THREAD

**Issue by Drimix20** [Drimix20/PB138-RSS-ctecka#22]
Mam dotaz, nynejsi implementace po odstraneni feedu pouze odstrani feed z konfigurace, tedy informace se uz nebudou dale stahovat. Ale v RssFeedContaineru zustanou drivejsi data. Nejspis by bylo vhodne, abych to upravil tak, aby vymazal data z kontajneru. Souhlasite?

**Comment by mayoturis** [comment]
ja súhlasím, myslím, že aj uživateľ by také chovanie očakával

**Comment by Drimix20** [comment]
Implementoval jsem to, tak to zkontrolujte pls.

**Comment by rzember** [comment]
Možno je chyba na mojej strane, ale na front ende sa to stále správa rovnako - tj. po odstránení feedu sa stále zobrazuje medzi ostatnými, akurát jeho položka v RemoveFeedDialogu zmizne.

**Comment by Drimix20** [comment]
Mrknu na to...

**Comment by Drimix20** [comment]
Spatne jsem porovnaval klic. Uz je to opravene. Nicmene stare data budou videt v gui, protoze jsou ulozeny v souboru a tudiz se nacitaji. Ale jde o to, ze dale se uz nebudou stahovat a aktualizovat.

**Comment by rzember** [comment]
Tak to uz je asi vsetko, aspon ja som nenasiel nic, co by nefungovalo :)

**Comment by Drimix20** [comment]
Ja taky myslim :)
