### ISSUE TITLE
Výnimka pri chybnej URL

### ISSUE THREAD

**Issue by mayoturis** [Drimix20/PB138-RSS-ctecka#23]
Ak sa pri pridávaní dialogu zadá chybná URL (chybný formát) tak vznikajú výnimky. 

Toto nemám úplne otestované ale tiež sa mi zdá, že ak sa pridá nový zdroj, do vypnutia aplikácie sa nenačítajú feedy do Containera (to ale nemusí byť chyba ale iba vlastnosť)

**Comment by mimaboci** [comment]
ten addfeed sa ani mne nezda

**Comment by Drimix20** [comment]
Bohuzel ted resim prednostni projekt, ale jak budu mit cas, tak se na to mrknu.

**Comment by Drimix20** [comment]
FIX: zkontroluj te to prosim
FIXED
