### ISSUE TITLE
Prezentace

### ISSUE THREAD

**Issue by Drimix20** [Drimix20/PB138-RSS-ctecka#24]
Meli bychom vytvorit prezentaci. Demovat budeme aplikaci z jar + configuration.xml?

**Comment by mayoturis** [comment]
neviem sa vyjadriť keďže neviem ako sa to robieva :) Tá prezentácia musia byť aj slidy? Lebo nejak ma nenapadá čo iné by tam mohlo byť okrem toho čo im ukážeme v aplikácii :)

Inak vedúci týmu by mal na začiatku predstaviť zadanie, tým a zhrnúť výsledky. Urobil by si to ty Martin? Viem, že si z nás už spravil najviac, ale aj práve preto, navyše máš z nás najviac skúseností, vedel by si najlepšie odpovedať na ich otázky :)

**Comment by rzember** [comment]
No ta prezentacia byva hlavnou castou obhajoby, myslim ale, ze na tento typ projektu by bolo fajn venovat demu nejaku vyznamnejsiu cast - do prezentacie nemusime davat veci ako napr. ako funguje UI, ale to proste ukazat na aplikacii

**Comment by Drimix20** [comment]
Dobre, muzu se toho tak nejak ujmout. Ale prezentace vseobecne rad nemam :D. Urcite bych vytvoril par slidu, popsat zadani, nas tym, ukazat, kdo co udelal (nejak rozumne, at to vypada pekne). Treba i zapsat koho nas co bavilo, zo bylo vyzva. Mozna by nebylo spatny tam dat i nejake informace o tom, ze na gitu jsme meli Issue, ktere jsme potrebovali resit. Bylo by vhodne upravit nasi projektovou wikinu do nejake hezke podoby. Dat ty veci, co jsme delali nejak dohromady k jmenu, nejak hezky to rozepsat a ucelit. Treba pridat i par obrazku z gui. Proste at wikina vystihuje nasi odvedenou praci. Na githabu to bude navzdy, tak at je k tomu nejaka hezka dokumentace... Tu bychom pak mohli taky ukazat, aspon zkracene.

**Comment by Drimix20** [comment]
Ja jsem zitra v praci a odpoledne budu resit jeste jeden projekt. Mame drivejsi deadline, ale zkusim se zitra dostat k te prezentaci. Pokud uz mate volno, bylo by dobre nejak ucelit, kdo co delal na te wiki a ja to pak jen hodin do prezentace...

**Comment by rzember** [comment]
Ja zajtra tiez nemam moc cas, ale v stredu pustim do tej wiki, medzitym tam mozete popisat vsetko, na com si spomeniete, ze ste pracovali, ja v tom nemam prehlad :D

pridam tam nejake obrazky z GUI, sablon, pokusim sa to nejak zabalit do slusneho formatu, atd.

**Comment by Drimix20** [comment]
Supr, dobre. Ja myslim, ze nebude vadit, kdyz prezentaci dodame az na obhajobu v patek ne?

**Comment by mayoturis** [comment]
do časti "Rozdělení práce" som dopísal na čom som robil

myslím, že by to malo stačiť v piatok

**Comment by rzember** [comment]
https://is.muni.cz/auth/el/1433/jaro2015/PB138/op/Hodnoceni_vyuky_a_organizace_projektu.html

" Každý řešitel navíc samostatně vypracuje závěrečnou zprávu o svém podílu na řešení projektu v rozsahu cca jedné stránky."

este toto davam na vedomie

**Comment by rzember** [comment]
Takže som upravil tú wiki, pridal tam nejakú dokumentáciu. Keby sa vám zdalo, že tam niečo chýba, alebo že som tam napísal nejakú hovadinu, tak to kľudne doplnte/upravte/vymažte.

Ešte by sa tam ale zišlo vytvoriť článok o backende, nejaký stručný popis toho, ako to funguje... o tom ale viete vy viac, než ja, takže keď budete mať niekto čas a chuť, dopíšte tam niečo prosím. Nemusí to byť pekné ani gramaticky správne, ja to už nejako dám dokopy.

A tie naše zápisky zo stretnutí som presunul do osobitnej sekcie, ako dôkaz, že sme na tom priebežne pracovali :D

**Comment by Drimix20** [comment]
Jj, ja tam dnes taky neco dopisu. Driv jsem nestihl a prezentaci taky udelam dneska.
