### ISSUE TITLE
Ukladani nakonfiurovanych zdroju feedu

### ISSUE THREAD

**Issue by Drimix20** [Drimix20/PB138-RSS-ctecka#8]
Nemeli bychom si ukladat i konfiguraci  zdroju feedu (odkud se maji stahovat + v jakem intervalu) nekam na disk a po spusteni aplikace nacit tuto konfiguraci. Tedy implementovat chovani, ze jakmile nadefinuju zdroj feedu, tak je trvaly i po znovu spusteni aplikace a odstranim ho jedine smazanim?

Tim bychom take docilili funkcionality, ze muzeme konfigurovat aplikaci i pomoci xml.

**Comment by mayoturis** [comment]
Odkiaľ sa majú sťahovať som pôvodne myslel, že by bolo v tom jednom súbore, ale to sme tam nejako nedoriešili (Issue #2). Čo sa týka ukladania toho intervalu sťahovania tam sa neviem vyjadriť, mne takto príde, že by ani nemusel existovať ak by stačilo, že by sa všetko stiahlo iba pri otvorení aplikácie alebo by bolo tlačítko obnoviť.

**Comment by Drimix20** [comment]
No jo, jenze ne kazdych 5 minud mas novy feedy a vetsinou rss ctecky jsou o tom, ze si muzes i navolit kolikrat ti to ma stahovat + stahni po stisknuti tlacitka. Muzeme to udelat vselijak, hlavne se domluvit. Ja jsem to spis myslel tak, ze bude nove xml:
![image](https://cloud.githubusercontent.com/assets/7419456/7731944/567b98d6-ff24-11e4-873d-819eb01954bc.png)

Vse bych do jednoho souboru nerval uz kvuli prehlednosti a v pripade poruchy neprijdu o vsechno naraz

Pri spusteni aplikace by praveze stahl vsechno, kdyby mel zadefinovane zdroje.

**Comment by mayoturis** [comment]
S tým súborom na konfiguráciu súhlasím. Ešte prosím vyjadri svoj názor/návrh aj v #2, lebo neviem ako sa teda budú ukládať tie feedy.

**Comment by Drimix20** [comment]
Delam na ukladani a nacitani konfigurace zdroju (externi xml soubor)
